### ISSUE TITLE
Level Loading and collision

### ISSUE THREAD

**Issue by NBatchelor1** [leederJosh/AlienAttack#13]
When loading the levels we are assigning values to the tiles based on the order they are loaded. This affects the different levels since we fall through a block such as Window in level 1 but then we also fall through the floor tiles in level 2

**Comment by leederJosh** [comment]
I am working towards this, hoping to be done in the next couple of days. It is a very large refactor. Instead of handling collision using tile constants we define I am changing it to Box2D which is a library in LibGDX that will handle all collisions internally. This works by adding object layers to our Tiled maps.

So far I have managed to create a Box2D Body object that can be moved and have also drawn "floor" boundaries in an object layer of Level One. The collision works fine. I just need to work on the speed to which the box can move around, applying the sprite to the box (it is currently a debug box) and applying boxes to entities. After this is done I will push to my branch and the addition of other maps should be fairly trivial.

This is a better way as it can be applied to all future levels with object layers and has not messed with the animation on the map. It could also allow us to set spawn points for entities and make the traps damage the player, but this will need more research.

**Comment by leederJosh** [comment]
All level collision works, spawn points have been implemented. Going to work on transitions now. After that all we need is levels with boundary, spawn and transitions objects in and levels will be finished.

**Comment by leederJosh** [comment]
Level transitions logic is implemented but you cannot travel between levels at the moment as there is no object layer on other levels at the moment

**Comment by leederJosh** [comment]
Level transition now fully works, using the aforementioned object layer "Level Transitions". It gets the position of the objects from the tiled map, draws a rectangle on the map and gives the rectangle to the given level. A method "hasPlayerFinished" in every level checks if the player is within the bounds of this rectangle and returns true when they are. This is called in the playscreen update and if true the level updates via the screen manager. 

Final note: If there are any further bugs for this first check the tiled map and ensure the transition box if of sufficient size (if in doubt draw it into the floor slightly as the players Y may not be above the rectangles Y and thus not in the box).
