### ISSUE TITLE
AI (should be done just under 2 weeks)

### ISSUE THREAD

**Issue by ehsanu** [leederJosh/AlienAttack#9]
I will need to add code to enemy class for AI and I expect to create new classes to get the whole functionality of AI working.

**Comment by jLeeder1** [comment]
Have made some progress with this, AI movement works. However there is a bug with the enemy shooting. We'll have a look into days session.

**Comment by jLeeder1** [comment]
Shooting and Movement are done, Boss AI needs to be implemented

**Comment by leederJosh** [comment]
Movement does not work properly now with box 2d (due to entities falling into holes and then never reaching their x destination defined in the AI class). Shooting still works fine for enemies though.

Thinking a contact listener could work for the movement (I.E listen fore contact between bottom vertices of entity and a floor object). If the contact at the left and right vertex stops firing as true then the entity should turn around.

**Comment by leederJosh** [comment]
I couldn't get the previous solution to work. I currently have two other options:

1. Make Boundary objects (rectangles) on the tile maps in tiles that entities will overlap and "collide with". These collisions will not cause the player to stop, they will instead act as sensors and when overlapped will change the entities moveRight boolean which controls their movement direction

2. Use raycasting to detect when an entities has struck a wall to their side or where the underneath of them is colliding with a map object (cast rays of half a tiles height downwards from the entity x when moving left, the left boundary, or from the entity x plus entity width).

Going to tr boundary objects first as this seems simpler and quicker to implement.

**Comment by leederJosh** [comment]
Had a different Idea. It goes back to the contact listener. I am going to watch  Brent Aureli's - Code School youtube tutorials where he creates Super mario. The enemies in this move between block points. I assume it uses objects on the screen (like the floor objects on the map) and a contact listener to reverse the entities direction when they come into contact with these blocks. Instead of showing the blocks however they will simply exists in the world(so you can't see them). Then I will use filtering to allow Player objects to pass through them but not other entities

**Comment by leederJosh** [comment]
Used the contact listener as stated above and works a treat. All entities move between boundaries on the map (these have been put into the appropriate places in all the maps). This also uses filtering so the player can move through entities and entities can move through entities.
